# Generated by Django 6.0.4 on 2026-04-14 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_alter_user_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='can_date_be_shared',
            new_name='can_data_be_shared',
        ),
    ]
